### ISSUE TITLE
EthKeyringController: call `destroy` when a keyring reference is dropped

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/core#1388]
This is part of the effort to consolidate keyring interactions between extension and mobile.
Originally proposed [here](https://github.com/MetaMask/core/issues/1103#issuecomment-1497403763).

#### Context
In the extension, ledgerKeyring.destroy and trezorKeyring.dispose methods are called to lock hardware keyrings, before calling EthKeyringController ’s `setLocked` method.

#### Solution
EthKeyringController should be responsible for calling an optional `keyring.destroy()` method when a reference to a keyring is being dropped (`lock`, `removeAccount`)

**Task list**
- [ ] Make changes to `EthKeyringController`
- [ ] Release new version of `EthKeyringController`
- [ ] Use new version of `EthKeyringController` in `KeyringController`
