### ISSUE TITLE
Fully migrate `eth-json-rpc-provider` into core monorepo 

### ISSUE THREAD

**Issue by xinnanyemm** [MetaMask/core#1551]
We would like to migrate the [`@metamask/eth-json-rpc-provider`](https://github.com/MetaMask/eth-json-rpc-provider) library into this repo to make it easier to maintain.

See the following checklist for instructions on accomplishing this: https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740

**Comment by MajorLift** [comment]
## Migration Checklist

### Phase A: Preparation in Original Repo
- https://github.com/MetaMask/core/pull/1755
  - [x] The dependency versions and configurations for typescript, eslint, prettier were aligned with the core monorepo.
    - [x] If migration target is ahead in dependency versions, consider updating core monorepo dependencies first.
    - [x] All resulting issues are resolved.
  - [x] Added missing files that are required in subpackages of the core monorepo (e.g. LICENSE).
  - [x] A final release of the migration target was made from the original repo (all future releases will be as partial releases from the core monorepo). 
  - [x] The migration target is moved into a temporary directory in core (`merged-packages/`) with git history fully intact. See: https://github.com/MetaMask/core/issues/1079#issuecomment-1700126302.
  - [x] The PR was **merged without squashing** to preserve the migrated git commit history.

* * *

### Phase B: Staging in `migrated-packages/`

#### 1. Remove files and directories that will be replaced by files in the monorepo root.
  - [x] **Remove**: `.github/`, `.git*`, `scripts/`, `.depcheckrc.json`, `.yarn/`, `.yarnrc.yml`, `yarn.lock`, `.editorconfig`, `.eslint*`, `.prettier*`, `.nvm*`.
  - [x] **Keep**: `src/`, `tests/`, `CHANGELOG.md`, `LICENSE`, `package.json`, `README.md`, `jest.config.js`, `tsconfig*.json`, `typedoc.json`. 
#### 2. Replace config files.
  - [x] Update `tsconfig*.json`, `typedoc.json`, `jest.config.js` to extend from corresponding files in root. Copy contents of corresponding files in other non-root packages.
  - [x] Keep TypeScript compiler flags. 
  - [x] Add tsconfig reference paths for non-root packages that are upstream dependencies of the migration target.
  - [x] Keep Jest coverage threshold values. 
  - [x] Add `deepmerge` as a devDependency.
#### 3. Align dependencies with monorepo.
  - [x] Remove redundant dependencies that are already listed in the root package.json.
  - [x] Bump remaining dependency versions so that they align with other non-root packages.
#### 4. License.
  - [x] If migration target uses a non-MIT license, add exception entries in the root `constraints.pro` file.  
  - [x] Make sure the new rule doesn't break any of the existing package.json files by running `yarn constraints`.

* * *

### Phase C: Integration

#### 1. Migrate
- [x] **Move migration target from `migrated-packages/` to `packages/`.**
- [x] Run `yarn install` in the root directory.
- [x] Check that all tests are passing in migration target by running `yarn workspace @metamask/[package-name] test`.

#### 2. Downstream updates
- [x] Add tsconfig reference paths for migration target in downstream packages and root.
- [x] Bump migration target version in downstream packages and root.

#### 3. Linter fixes
- [x] Apply yarn constraints fixes to migration target package.json file: `yarn constraints --fix` (run twice).
- [x] Identify validator fixes for CHANGELOG using `yarn workspace @metamask/[package-name] changelog:validate` and apply the diffs. 

* * *

### Phase D: Repair errors in downstream packages
  - [ ] `network-controller`
  - [ ] `selected-network-controller`
  - [ ] `transaction-controller`
  - [ ] `gas-fee-controller`

* * *

### Phase E: Completion

#### 1. Release
- [x] Add migration target to README dependency graph using the `generate-dependency-graph` build script.
- [ ] Publish new migration target version from core as a partial release by following [these steps](https://github.com/MetaMask/core/blob/main/docs/contributing.md#releasing).
- [ ] Add tags for previous releases of migration target.

#### 2. Cleanup
- [ ] Migrate branches/issues/PRs from original repo into core.
- [ ] Archive original repo.
- [ ] Point to core in original repo's README.
