### ISSUE TITLE
Shared Libraries - Reduce maintenance burden for core wallet functionality - Q423

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1780]
### 2023/Q4/O1/KR2 Description: 
5 libraries are migrated to core monorepo
Some of the core wallet functionality is held in utility libraries. We https://github.com/MetaMask/core/issues/1079 the set of libraries that need to be migrated into the core monorepo.

In order to fully complete this task, we may need to raise the code quality of these libraries by converting the existing code to TypeScript, upgrading the minimum Node version, upgrading Yarn and Jest, upgrading our ESLint packages along with any configuration, upgrading other dependencies to their latest versions, and aligning the project to match our module template.

Slated libraries for migration (we were able to start on these at the very end of Q3 so we will add a few more to this list to replace the ones we finish ahead of time):

- [ ]  @metamask/utils
- [x]  @metamask/json-rpc-engine
- [x]  @metamask/eth-json-rpc-provider
- [x]  @metamask/json-rpc-middleware-stream

### 2023/Q4/O1/KR1 Description: 
5 extension controllers are merged into core monorepo 
Much of the core wallet functionality is managed by specific libraries known as “controllers”. We [previously designated](https://github.com/MetaMask/core/issues/700) the set of controllers used by the extension that were eligible for merging into the core monorepo. We will choose a few from this list that we are confident we can complete without a need to collaborate with any other team.
In order to fully complete this task, we may need to raise the code quality of these controllers by refactoring the existing code, simplifying the existing API, adding missing tests, improving the quality of existing tests, or adding missing documentation.

Controllers to be merged:

- AccountTracker (core) / CachedBalances (extension) [there may be some overlap with accounts]
- TokenBalances
- TokenDetection (core) / DetectTokens (extension)
- PermissionLog
- ENS [stretch goal]
  - [ ] https://github.com/MetaMask/core/issues/1605
