### ISSUE TITLE
Shared Libraries - 2023/Q4/O1/KR2 - 5 libraries are migrated to core monorepo

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#1781]
Some of the core wallet functionality is held in utility libraries. We [previously designated](https://github.com/MetaMask/core/issues/1079) the set of libraries that need to be migrated into the core monorepo.

In order to fully complete this task, we may need to raise the code quality of these libraries by converting the existing code to TypeScript, upgrading the minimum Node version, upgrading Yarn and Jest, upgrading our ESLint packages along with any configuration, upgrading other dependencies to their latest versions, and aligning the project to match our module template.

Slated libraries for migration (we were able to start on these at the very end of Q3 so we will add a few more to this list to replace the ones we finish ahead of time):

- [ ] @metamask/utils
- [x] @metamask/json-rpc-engine
- [x] @metamask/eth-json-rpc-provider
- [x] @metamask/json-rpc-middleware-stream
