### ISSUE TITLE
Script to pull information around changes needed to libraries

### ISSUE THREAD

**Issue by desi** [MetaMask/core#1814]
We should have a script that runs and pulls information around needed updates for all the libraries (all repos).

The script should determine the following information:

- [x] MetaMask/module-lint#12
- [x] MetaMask/module-lint#11
- [x] MetaMask/module-lint#10
- [x] MetaMask/module-lint#9
- [x] MetaMask/module-lint#8
- [x] MetaMask/module-lint#7
- [ ] MetaMask/module-lint#6

**Comment by desi** [comment]
Closing this epic. There is one outstanding ticket but the ticket can remain while closing out the rest of this epic
