### ISSUE TITLE
Document process guide for migrating libraries into core monorepo

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#1834]
## Overview

As part of Shared Libraries Q3/Q4 OKRs, the team would like to document a process guide for migrating libraries into this monorepo. 

This entails two tasks:

1. The process needs fine-tuning. During the course of migration efforts utilizing the initial instructions (https://github.com/MetaMask/core/issues/1079#issuecomment-1700126302), several blockers, points of caution, and gaps were identified. These issues need to be resolved and the solutions documented. 

2. The lessons and solutions from the initial migrations need to be compiled into a step-by-step guide that is granular and streamlined enough to be easily followed by the team (and potentially external contributors) to migrate any library into the core monorepo without significant adjustments or delays. 

### Fine-tuning

- [ ] Implement script for porting release tags with package-name prefixes: https://github.com/MetaMask/core/issues/1800.
- [ ] Modify `auto-changelog` validator to handle inconsistent package-name prefixes in the ported tags of renamed packages: https://github.com/MetaMask/core/issues/1795.
- [ ] **WONTFIX**: Fix tag diffs between migrated commits and post-migration commits in the monorepo including the entire commit history of core.
- [ ] Easily repeatable solution for migrating issues and PRs from the original repo.

### Documentation

- [ ] Document all steps in process and identify the best order and grouping for executing these tasks: https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740.
- [ ] Compile a comprehensive, standardized process guide.

**Comment by MajorLift** [comment]
Closed by https://github.com/MetaMask/core/pull/2071
