### ISSUE TITLE
Post-migration clean-up for `@metamask/eth-json-rpc-provider`

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#1838]
## Overview

After the process for migrating `eth-json-rpc-provider` into the `packages/` directory of the core monorepo is completed, there are a few follow-up and clean-up tasks left to perform.

### Source repo

- [ ] Transfer branches/issues/PRs from the source repo into the core monorepo.
  - [ ] Blocked by #1835 
- [ ] Leave a note in the source repo's README announcing the migration and pointing to core.
- [ ] Sunset `/latest` and `/staging` docs on GitHub Pages (or migrate to core?).
- [ ] Archive the source repo to prevent any changes from being pushed to it going forward.

### Core

- [ ] Update contents of `packages/eth-json-rpc-provider/README.md` to reflect new status as a non-root package in the monorepo.
- [ ] Use the `yarn create-release-branch` tool to publish a new release of core with the migrated package listed as an ADDED change.
  - [ ] Record any changes made to monorepo packages during the migration process in their respective changelogs.
- [ ] Fix downstream errors that were marked with `@ts-expect-error TODO:` during the migration process.
  - #1823 

## References

- Previous step in migration: #1738. 
- See https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740 for context on the migration process.
- See https://github.com/MetaMask/core/issues/1079#issuecomment-1700126302 for context on the migration process.
