### ISSUE TITLE
Post-migration clean-up for `@metamask/eth-json-rpc-provider`

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#1842]
## Overview

After the process for migrating `eth-json-rpc-provider` into the `packages/` directory of the core monorepo is completed, there are a few follow-up and clean-up tasks left to perform.

### Core

- [x] MetaMask/core#1846
- [x] Add migration target to README dependency graph using the `generate-dependency-graph` build script.
- [ ] Fix downstream errors that were marked with `@ts-expect-error TODO:` during the migration process.
  - [ ] MetaMask/core#1823
- [x] Use the `yarn create-release-branch` tool to publish a release of core with a new version for the migrated package and any updated downstream packages.
  - [x] MetaMask/core#1849 
- [ ] ~Publish typedocs with GitHub Pages.~
  - [ ] Blocked by https://github.com/MetaMask/core/issues/1845

### Source repo

- [x] MetaMask/eth-json-rpc-provider#34
  - ~Blocked by MetaMask/core#1835~
- [x] MetaMask/eth-json-rpc-provider#37
- ~MetaMask/eth-json-rpc-provider#35~
- [ ] MetaMask/eth-json-rpc-provider#32
  - [x] Blocked by all of the above.

## References

- Previous step in migration: MetaMask/core#1738. 
- See https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740 for context on the migration process.
- See https://github.com/MetaMask/core/issues/1079#issuecomment-1700126302 for context on the migration process.
