### ISSUE TITLE
Post-migration cleanup for `@metamask/json-rpc-middleware-stream`

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/core#1982]
### Tasks

- ~Update README to reflect new status as a non-root package in core monorepo.~
- [x] Add migration target to README dependency graph using the `generate-dependency-graph` build script.
  - [x] https://github.com/MetaMask/core/pull/1991
- ~Fix downstream errors that were marked with `@ts-expect-error TODO:` during the migration process.~
- [x] Record any changes made to packages during the migration process in their respective CHANGELOGs.
  - [x] https://github.com/MetaMask/core/pull/2003
- [ ] Use the `yarn create-release-branch` tool to publish a release of core with a new version for the migrated package and any updated downstream packages.
- [ ] ~Publish typedocs with GitHub Pages.~

### References
- See [#1551 (comment)](https://github.com/MetaMask/core/issues/1551#issuecomment-1745665740) for context on the migration process.
- See [#1079 (comment)](https://github.com/MetaMask/core/issues/1079) for context on the migration initiative.

**Comment by desi** [comment]
@MajorLift Can you add an estimate to this one?
