### ISSUE TITLE
Shared Libraries - Module Lint backed Dashboard

### ISSUE THREAD

**Issue by desi** [MetaMask/core#3838]
**2024/Q1/O4/KR1 Description:**
There are various libraries across our organization that need continued maintenance work and the responsibility of this maintenance work is spread across many teams. The Shared Libraries team has been mostly focused on moving and maintaining libraries which have core wallet functionality but in the process of doing this work we have started to create a tool which can help teams stay on top of this work for libraries in their scope of work. This tool is called “[module-lint](https://github.com/MetaMask/module-lint)”. Module-lint started as a way for us to complete the library migration and maintenance work we have but we have realized this could and should be a product / tool we provide to other teams. The KR allows us to continue building the MVP of this tool and begin to help other teams take advantage of using it.

MVP inclusions target:

- [x] Node.js version (https://github.com/MetaMask/module-lint/issues/12)
- [x] Yarn version/configuration (https://github.com/MetaMask/module-lint/issues/11)
- [x] ESLint versions/configuration (https://github.com/MetaMask/module-lint/issues/9)
- [x] Jest version/configuration (https://github.com/MetaMask/module-lint/issues/10)
- [x] TypeScript version/configuration (https://github.com/MetaMask/module-lint/issues/8)
- [x] TypeDoc version/configuration (https://github.com/MetaMask/module-lint/issues/47)
- [x] auto-changelog version/configuration (https://github.com/MetaMask/module-lint/issues/48)
- [x] allow-scripts version/configuration (https://github.com/MetaMask/module-lint/issues/51)
- [ ] ~npm package scripts for building, linting, changelog validation, tests~ This will already be covered by the above
- [ ] GitHub actions (nice to have) (https://github.com/MetaMask/module-lint/issues/52)
- [ ] Checks for general module template adherence (https://github.com/MetaMask/module-lint//issues/6)
