### ISSUE TITLE
Streamlining KeyringController API

### ISSUE THREAD

**Issue by mikesposito** [MetaMask/core#3871]
This issue aims to provide a list of observations and possible proposals to simplify the `KeyringController` API, removing unnecessary, redundant, out-of-scope, and confusing methods.

The `KeyringController` responsibilities should be the following (ideally, this is not written on any stone):
* Hold keyrings instances
* Provide functionalities to lock and unlock the wallet
* Keep in sync its state with the state of each keyring
* Route action calls for a specific account to the corresponding keyring that holds the account, or in other words, it should know which Keyring a specific account belongs to, and which actions are supported

**Comment by mikesposito** [comment]
## Hold Keyrings
The first responsibility listed is already effectively implemented: `KeyringController` holds all keyring instances in its `#keyrings` array.

**Comment by mikesposito** [comment]
## Locking and Unlocking
The second responsibility, /providing functionalities to lock and unlock the wallet/, is also already implemented, but we can probably do some refactoring to make it easier to use, and reduce the API coverage that it takes. Currently, we have these methods:
* `isUnlocked`: in essence, it simply returns the value of  `isUnlocked` from the `KeyringController` state. 
* `verifyPassword`: Provides a way to check the correctness of a certain password. This is used in certain cases where the user should be prompted for the password again (e.g. before SRP reveal), even if the wallet is already unlocked.
* `setLocked`: Wipes the keyring array from memory, and sets the wallet as locked.
* `submitPassword`: Unlocks the wallet with a password, extracting all serialised keyrings from the encrypted vault, and restoring them in the `#keyrings` array.
* `submitEncryptionKey`: Same as `submitPassword`, but with an encryption key that is usually derived from the password. This is mainly needed for MV3 compatibility.

We could do a couple of small improvements here:
* We don’t necessarily need the `isUnlocked` method, as that should be easily accessible with `KeyringController.state.isUnlocked`: we can consider it as redundant.
* `submitPassword` / `submitEncryptionKey`: we could take away some ambiguity, providing a unique method to unlock the wallet, and that could be, for simplicity, named `setUnlocked` (to reflect `setLocked`): this method should then provide a way to unlock the wallet using one of the two different possible methods (password / encryption key + salt).

**Comment by mikesposito** [comment]
## Keep in sync its state with the state of each keyring
This is were things become a little more tricky. Currently, every time one of the “keyring actions” provided by the `KeyringController` (e.g. `addNewAccount`, `removeAccount`..) is executed, in case that action is considered to be mutating the state (e.g. an account is added or removed), each keyring is serialised, re-encrypted and saved into the vault, and its list of accounts is then replicated in the `KeyringController`’s state.

This mechanism is our strategy to keep the vault, the state of the `#keyrings`, and the `KeyringController` state all in sync. But what happens when a client calls some method on the keyring directly? Well, in that case the keyring would potentially mutate, but the vault and the `KeyringController` state would be left behind! 

Unfortunately, as we’ll observe in the next paragraph “Route action calls for a specific account to the corresponding keyring”, not all possible “keyring actions” are supported by the `KeyringController` API, and this leads to client needing to call methods on Keyrings directly, bypassing `KeyringController`: this is a real case scenario for Hardware Keyrings.

This is where the KeyringController’s  `persistAllKeyrings` method comes into play: it can be used by external clients to serialise all keyrings, save them encrypted into the vault, and reflect accounts held by them in the `KeyringController` state. The problem with that, as you can imagine, is that this moves this responsibility to clients.

Including all possible supported methods in `KeyringController` would probably be the easiest solution, but would also do the exact opposite of what these observations are for.  
An alternative that would remove the need for a `persistAllKeyrings` method could be an event subscription between KeyringController and the single Keyrings included in the array: each Keyring could be an event emitter to which the KeyringController is subscribed to, and at each event emitted the KeyringController would execute the syncing operations. This way, clients don’t event have to know which method/action is going to mutate the state, because it will be kept in sync automatically, under the KeyringController’s hood.

**Comment by mikesposito** [comment]
## WIP: Route action calls for a specific account to the corresponding keyring
As already disclosed in the previous paragraphs, not all keyrings have the same features, and some of them present different APIs, in some cases very similar to each other, yet not identical. 

The way clients went through these differences up until now has been to rely on these two methods that `KeyringController` provides:
* `getKeyringForAccount` 
* `getKeyringsByType`
Thanks to these two methods, clients can get direct access to Keyring instances, and call methods directly on them, bypassing KeyringController API limits. 

A brilliant proposal from the accounts team, aims to turn KeyringController into a router, forwarding requests to keyrings, “routing” them based on the targeted account: this would solve the issue completely.

To make that into an easier goal, we could cut off some of the `KeyringController` methods that are not particularly relevant, or that provide features that can be accessed or implemented in other ways.

### Methods related to  the QR Keyring
Some of the methods related to the QRKeyring are included in the `KeyringController`: this is somehow a privilege that the QRKeyring has over other _less standard_ keyrings, like other hardware keyrings. 
These methods:
* restoreQRKeyring
* resetQRKeyringState
* getQRKeyringState
* submitQRCryptoHDKey
* submitQRCryptoAccount
* submitQRSignature
* cancelQRSignRequest
* cancelQRSynchronization
* connectQRHardware
* unlockQRHardwareWallet
Are just exposing methods from the underlying QRKeyring instance. So, actually, if the client can use `getKeyringForAccount`, or `getKeyringsByType` (or even `getOrAddQRKeyring`), it can get access to the keyring directly and do the same. 

There’s a caveat that is worth noting: currently, `KeyringController` is subscribed to events emitted by QRKeyring, as the extension uses those to display modals related to QR syncing and signing. This will probably make the QRKeyring trickier to align with other keyrings, and also `getOrAddQRKeyring` difficult to be removed along the others (as the event subscription happens in there). 
Perhaps, this would be easier if the event subscription between KeyringController and keyrings described in the previous paragraph “Keep in sync its state with the state of each keyring” is in place, as the QRKeyring will be able to use that channel to post its updates.

**Comment by mikesposito** [comment]
## Proposed solutions

### Lock / Unlock
- [ ] Remove `isUnlocked` method
- [ ] Refactor `submitPassword` and `submitEncryptionKey` into one single `setUnlocked` method

---

### State syncing
#### Phase 1
- [ ] Add `subscribe` method to the Keyring type
#### Phase 2
- [ ] Add `subscribe` method to HDKeyring
- [ ] Add `subscribe` method to SimpleKeyring
- [ ] Add `subscribe` method to QRKeyring
- [ ] Add `subscribe` method to LedgerKeyring
- [ ] Add `subscribe` method to TrezorKeyring
#### Phase 3
- [ ] KeyringController should subscribe to all added keyrings
- [ ] Remove `persistAllKeyrings` method

---

### KeyringController redundant methods removal
- [ ] Remove redundant QRKeyring methods from KeyringController:
  - getQRKeyring
  - restoreQRKeyring
  - resetQRKeyringState
  - getQRKeyringState
  - submitQRCryptoHDKey
  - submitQRCryptoAccount
  - submitQRSignature
  - cancelQRSignRequest
  - cancelQRSynchronization
  - connectQRHardware
  - unlockQRHardwareWallet

---

### Remove redundant HDKeyring methods (and features) from KeyringController
- [ ] First mnemonic generation and first account creation should happen in HDKeyring `.init` (instead of KeyringController)
- [ ] Assess if `verifySeedPhrase` can be removed, and `addNewAccount` along with it
- [ ] Remove `exportSeedPhrase` from KeyringController
 
---
 
### Remove redundant SimpleKeyring methods from KeyringController
- [ ] Move `importAccountWithStrategy` logic from KeyringController to SimpleKeyring

**Comment by mikesposito** [comment]
Thanks for taking a close look @mcmire! 

> Instead of setLocked and setUnlocked, what do you think about calling these methods lock and unlock? To me, "setXXXX" implies a simple setter, but this would be doing more than that, so it seems like we can use more "natural language" to reflect a more complicated action.

Agreed! `lock` and `unlock` make more sense

> If KeyringController subscribes to keyrings that are added, will/should there ever be a way to remove keyrings, and if so, should it also unsubscribe when keyrings are removed?

True, they will also have to provide a way to unsubscribe 

> I see in the KeyringController that there are three "addAccount" methods: addNewAccount, addNewAccountForKeyring, and addAccountWithoutUpdate. In particular I'm curious when addAccountWithoutUpdate is used and whether there is another way to do what it's doing without making a new method. The JSDocs for this method says "Adds a new account to the default (first) HD seed phrase keyring without updating identities in preferences", but the KeyringController shouldn't care about preferences, so perhaps this is old?

That is correct. I didn't mention `addAccountWithoutUpdate` in this analysis because it will most likely be removed when solving this issue: https://github.com/MetaMask/core/issues/3848
As you said, that is not KeyringController's responsibility anymore 

> I took a closer look at the proposal by the accounts team, in particular the Proposed API section, and there are a number of differences as compared to your proposal. What are your thoughts on this API?

This issue is meant to be a step in that direction, aligning keyring features better so that it will be easier to apply that proposed API. 
We should also note that some parts of the linked accounts team proposal might be outdated, as `AccountsController` has been introduced, EthKeyringController/KeyringController have been merged together, and now both Extension and Mobile use the same KeyringController

> You noted above that the handleRequest method which the accounts team proposed could be used to solve the problem that in some cases consumers go straight to keyring objects to perform certain actions. However, in the accounts team's proposal, they use handleRequest not as a way of solving this problem but replacing methods that seem to delegate directly to the keyring, e.g. signTransaction, signMessage, etc.

Ideally, all keyring-specific methods that consumers currently use on Keyrings object directly should be accessed through `handleRequest`: this can include `signTransaction` and `signMessage`, but perhaps also `exportAccount` and other keyring-specific methods (indeed, these are not included in the accounts team proposal).

I do think that the `handleRequest` method requires a more detailed technical proposal as the main problem would be to give a way to consumers (and to KeyringController) to know which features are supported by each type of keyring - this is the reason why in this issue we are not introducing that yet

> You also mention that we can remove all the QR methods, but just to be clear, what do you intend on replacing these with?

The idea is to simply remove them, as consumers can access them using other KeyringController methods:
E.g. `restoreQRKeyring` can be accessed through:
```typescript
(await keyringController.getOrAddQRKeyring()).restoreQRKeyring

// or

keyringController.getKeyringsByType('qr')[0].restoreQRKeyring
```
This is how also other hardware keyrings are accessed by consumers

**Comment by mcmire** [comment]
@mikesposito Thanks for the replies! Seems like a well-thought-out plan in total 👍🏻

**Comment by mcmire** [comment]
@mikesposito Can I close this ticket? It seems like this was only ever intended to be a planning ticket, and not an epic. Since we created a plan, it seems that this ticket has served its purpose. Is this true?

**Comment by mikesposito** [comment]
@mcmire yes that makes sense, we can close this
