### ISSUE TITLE
Normalize the API between each network controller

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#971]
We should make the API for each network controller more similar, to make merging them simpler.

Lets evaluate each method on a case-by-case basis, and evaluate what makes the most sense for the merged controller. Then we can migrate each controller to match whatever we think is best for that method/use-case.

### Changes needed in `@metamask/network-controller`:

- [ ] Implement `getProviderAndBlockTracker`, which will return a proxied provider and block tracker (https://github.com/MetaMask/controllers/issues/1018)
- [ ] Rename `properties` state to `networkDetails` (https://github.com/MetaMask/controllers/issues/1019)
- [ ] Replace `network` and  `isCustomNetwork` state with `currentNetworkType` state (https://github.com/MetaMask/controllers/issues/1020)
- [ ] Replace `providerConfig` setter with an async `initializeProvider` method (https://github.com/MetaMask/controllers/issues/1021)
- [ ] Add async `getEIP1559Compatibility` method that populates the `networkDetails` state if it's not set yet (https://github.com/MetaMask/controllers/issues/1022)
- [ ] Add `resetConnection` method (https://github.com/MetaMask/controllers/issues/1023)
- [ ] Add `rollbackToPreviousProvider` method (https://github.com/MetaMask/controllers/issues/1024)

### Changes needed in `metamask-extension`:

- [x] Add Infura project ID to constructor and remove `setInfuraProjectId` method (https://github.com/MetaMask/metamask-extension/pull/16884)
- [ ] Stop extending `EventEmitter` (https://github.com/MetaMask/metamask-extension/issues/16945)
- [ ] Replace `network` state with `currentNetworkType` state (https://github.com/MetaMask/metamask-extension/issues/16946)
- [ ] Make `initializeProvider` and `lookupNetwork` async (https://github.com/MetaMask/metamask-extension/pull/16881)
- [x] Make `setProviderType` synchronous (https://github.com/MetaMask/metamask-extension/pull/16879)
- [x] Make these methods private: (https://github.com/MetaMask/metamask-extension/pull/16882 and https://github.com/MetaMask/metamask-extension/pull/16883)
  - `getLatestBlock`
  - `verifyNetwork`
  - `setNetworkState`
  - `setNetworkEIPSupport`
  - `clearNetworkDetails`
  - `setProviderConfig`
- [ ] Remove these methods, instead using state to get this information (https://github.com/MetaMask/metamask-extension/issues/16947)
  - `getNetworkState`
  - `isNetworkLoading`
  - `getCurrentChainId`
  - `getCurrentRpcUrl`
  - `getProviderConfig`
  - `getNetworkIdentifier`

**Comment by Gudahtt** [comment]
I'll start to go over the differences.

The constructors are effectively the same except that the mobile network controller accepts the infura project ID, whereas on the extension that gets set later. Both accept initial state. The extension controller calls its constructor parameter `opts`, but it is effectively just the state despite the confusing name. We can update the extension controller to use a more sensible name for that parameter, and to support setting the Infura RPC URL directly. This would also let us get rid of the `setInfuraProjectId` method, which only exists on the extension, and is only called immediately upon construction.

**Comment by Gudahtt** [comment]
The extension network controller extends `EventEmitter`, but the mobile controller does not. We don't need this, we have our own messaging system that we can use for events instead.

**Comment by Gudahtt** [comment]
Both controllers have a `provider` property. On mobile, this is the provider for the current selected network. On extension, it's a _proxy_ to the provider for the current selected network. The proxy ensures we don't keep using a provider after we've switched away from it.

We'll be getting rid of the proxy soon once we add multi-network support, but until then I think we should keep using a proxy. It's too easy to mess up and keep a stale reference to the wrong provider. That means we'll have to migrate the proxy logic to mobile.

Related to this, the extension exposes a block tracker whereas mobile doesn't (they don't even use one internally). We need this, so we'll have to add that to mobile as well.

**Comment by Gudahtt** [comment]
The stores have a few differences. The mobile controller has just one store with the following contents:

* `network` - The "network type", set to "loading" while loading, or to "RPC" when using a custom RPC, but is otherwise set to the current selected Infura network.
* `isCustomNetwork` - A redundant boolean
* `providerConfig` - The provider configuration for the current network
* `properties` - Properties for the current selected network. Currently just tracks whether the current network is EIP1559 compatible or not.

The extension state is split into four parts:
* `provider` - The provider config
* `previousProviderStore` - The previous provider config
* `network` - Either "loading", or the network ID for the current selected network
* `networkDetails` - the same as `properties` on the mobile store


Both have provider config, that's good. `properties` and `networkDetails` are essentially interchangeable, all we need to do there is decide upon which name to use. `isCustomNetwork` seems easy to get rid of.

We need some way to track whether a network switch is in progress. The other details tracked by `network` on the extension are redundant, it's just the loading state we need to keep. And similarly, `network` on mobile is redundant with the provider config, except for the loading state. Maybe we'll still find it convenient to track whether the current selected network is Infura or custom, but the network ID part is totally useless.

We use the previous provider store on the extension to switch back to the previous choice if we can't connect, so we'll need to keep that.

So here's my proposed unified state, roughly:
* `providerConfig - self explanatory
* `previousProviderConfig` - Self-explanatory.
* `currentNetworkType`  - Either "loading", "Infura", or "custom"; something like that
* `networkDetails` - The same as the current `networkDetails`/`properties`

**Comment by Gudahtt** [comment]
Provider initialization is performed via the `providerConfig` setter on mobile, and the `initializeProvider` function on extension. Both of these are "synchronous" actions that trigger async work. We should migrate both to use `initializeProvider`, and make the function properly async so we can test it more easily.

**Comment by Gudahtt** [comment]
The extension method `getEIP1559Compatibility` seems redundant at first (this information is already in state!), except that it allows you to _block_ on retrieving this information if we don't have it yet. We make use of that in the transaction controller.

We could roll this into the "loading" state potentially, but I'm not sure whether we want to. For now it seems easier to keep this.

**Comment by Gudahtt** [comment]
Seemingly `setProviderType` is async on the extension for no reason. It does nothing asynchronously. Making this synchronous would bring it in-line with mobile.

**Comment by Gudahtt** [comment]
The extension method `resetConnection` is used in the extension for the "Reset Account" button, useful for development to reset the network connection and all related caches in middleware. We'll need to keep this for now.

**Comment by Gudahtt** [comment]
On the extension, `rollbackToPreviousProvider` is needed to restore the previous network configuration. I think we need this too, for the same reason we need to keep the previous provider state.

**Comment by Gudahtt** [comment]
The following methods are present in the extension network controller API but never used externally:

- `getLatestBlock`
- `verifyNetwork`
- `setNetworkState`
- `setNetworkEIPSupport`
- `clearNetworkDetails`
- `setProviderConfig`

The following methods are present in the extension network controller API but are redundant (replacable by accessing state instead):

- `getNetworkState`
- `isNetworkLoading`
- `getCurrentChainId`
- `getCurrentRpcUrl`
- `getProviderConfig`
- `getNetworkIdentifier`

**Comment by Gudahtt** [comment]
That covers all of the differences! The remaining API is:

* constructor (accepts messenger, state, and infuraProjectId)
* async `initializeProvider
* async `lookupNetwork`
* async `getEIP1559Compatibility`
* `resetConnection`
* `rollbackToPreviousProvider`
* `getProviderAndBlockTracker`
* `setProviderType`
*` setRpcTarget`

We can unify the state to be a single `state` property as well. We don't need any other properties.

At some point in the future we should consider unifying `setProviderType` and `setRpcTarget` into a single method (e.g. `switchNetwork`), but we don't need to do that before the merge.

**Comment by Gudahtt** [comment]
Closing because the work has been broken into separate issues

**Comment by kumavis** [comment]
congrats on merge :tada:
